import { context, trace } from '@opentelemetry/api';

import { createBetterAuthClientAdapter } from '#adapters/auth/client-adapter.js';
import {
  acceptInvitationMutation,
  createInvitationMutation,
  invitationsInvalidates,
  invitationsQuery,
  publicInvitationQuery,
  revokeInvitationMutation,
  activePadSessionQuery,
  activePadSessionInvalidates,
  activeSourceUpdateRequestQuery,
  changePasswordMutation,
  configQuery,
  approveDocumentMutation,
  approveDocumentCommentMutation,
  approveDocumentLinkMutation,
  addDocumentCommentMutation,
  apiTokensInvalidates,
  apiTokensQuery,
  createApiClient,
  createApiTokenMutation,
  createDocumentMutation,
  createDocumentTypeMutation,
  createPadSessionMutation,
  createSavedSearchMutation,
  createSignatureRecordMutation,
  createSourceUpdateRequestMutation,
  cancelSourceUpdateRequestMutation,
  completeSourceUpdateRequestMutation,
  decideSourceUpdateRequestMutation,
  deleteDocumentFileMutation,
  deleteDocumentMutation,
  deleteDocumentTypeMutation,
  deleteDocumentCommentMutation,
  deleteSavedSearchMutation,
  disconnectPadSessionMutation,
  disableTwoFactorMutation,
  directFileUploadMutation,
  documentFileQuery,
  documentLinksInvalidates,
  documentLinksQuery,
  documentCommentsInvalidates,
  documentCommentsQuery,
  documentQuery,
  documentTypesInvalidates,
  documentTypesQuery,
  documentsInvalidates,
  documentsQuery,
  enableTwoFactorMutation,
  exportDocumentsMutation,
  finalizeFileUploadMutation,
  meInvalidates,
  meQuery,
  moveDocumentFileMutation,
  joinOwnPadSessionMutation,
  linkDocumentsMutation,
  passkeysInvalidates,
  passkeysQuery,
  pendingSourceUpdateRequestsQuery,
  registerPasskeyMutation,
  removePasskeyMutation,
  revokeApiTokenMutation,
  purgeDocumentMutation,
  padSessionInvalidates,
  padSessionStateQuery,
  closePadSessionMutation,
  consumePadStrokesMutation,
  consumePadSubmissionMutation,
  requestFileUploadMutation,
  requestMagicLinkMutation,
  requestPadSignatureMutation,
  setPadCurrentDocumentMutation,
  sharePadSessionMutation,
  savedSearchesInvalidates,
  savedSearchesQuery,
  requestPasswordResetMutation,
  requireDocumentSignatureMutation,
  resetPasswordMutation,
  restoreDocumentMutation,
  signInMutation,
  signInPasskeyMutation,
  signInSocialMutation,
  signOutMutation,
  signUpMutation,
  setUserPreferenceMutation,
  signatureRecordsInvalidates,
  signatureRecordsQuery,
  sourceUpdateRequestsInvalidates,
  submitPadStrokesMutation,
  tenantSettingsInvalidates,
  tenantSettingsQuery,
  tenantAccountsQuery,
  updateDocumentMutation,
  renameDocumentTypeMutation,
  updateTenantSettingsMutation,
  updateUserMutation,
  unapproveDocumentMutation,
  unlinkDocumentsMutation,
  waiveDocumentSignatureMutation,
  uploadDocumentFileMutation,
  userPreferenceInvalidates,
  userPreferenceQuery,
  verifyTotpMutation,
  trashedDocumentsQuery,
} from '#core/client/index.js';

const traceparent = (): string | undefined => {
  const spanContext = trace.getSpanContext(context.active());
  if (!spanContext) return undefined;
  const flags = spanContext.traceFlags.toString(16).padStart(2, '0');
  return `00-${spanContext.traceId}-${spanContext.spanId}-${flags}`;
};

const apiClient = createApiClient({ baseUrl: '', traceparent });
const authClient = createBetterAuthClientAdapter('');

export const actions = {
  config: configQuery(apiClient),
  invitations: invitationsQuery(apiClient),
  createInvitation: createInvitationMutation(apiClient),
  revokeInvitation: revokeInvitationMutation(apiClient),
  invitationsInvalidates,
  publicInvitation: (token: string) => publicInvitationQuery(apiClient, token),
  acceptInvitation: acceptInvitationMutation(apiClient),
  me: meQuery(apiClient),
  meInvalidates,
  documents: (filter: Parameters<typeof documentsQuery>[1]) =>
    documentsQuery(apiClient, filter),
  trashedDocuments: trashedDocumentsQuery(apiClient),
  document: (documentId: string) => documentQuery(apiClient, documentId),
  documentComments: (documentId: string) =>
    documentCommentsQuery(apiClient, documentId),
  addDocumentComment: addDocumentCommentMutation(apiClient),
  approveDocumentComment: approveDocumentCommentMutation(apiClient),
  deleteDocumentComment: deleteDocumentCommentMutation(apiClient),
  documentCommentsInvalidates,
  documentLinks: (documentId: string) => documentLinksQuery(apiClient, documentId),
  documentLinksInvalidates,
  documentFile: (documentId: string, fileId: string) =>
    documentFileQuery(apiClient, documentId, fileId),
  createDocument: createDocumentMutation(apiClient),
  updateDocument: updateDocumentMutation(apiClient),
  linkDocuments: linkDocumentsMutation(apiClient),
  approveDocumentLink: approveDocumentLinkMutation(apiClient),
  unlinkDocuments: unlinkDocumentsMutation(apiClient),
  approveDocument: approveDocumentMutation(apiClient),
  unapproveDocument: unapproveDocumentMutation(apiClient),
  waiveDocumentSignature: waiveDocumentSignatureMutation(apiClient),
  requireDocumentSignature: requireDocumentSignatureMutation(apiClient),
  deleteDocument: deleteDocumentMutation(apiClient),
  restoreDocument: restoreDocumentMutation(apiClient),
  purgeDocument: purgeDocumentMutation(apiClient),
  requestFileUpload: requestFileUploadMutation(apiClient),
  finalizeFileUpload: finalizeFileUploadMutation(apiClient),
  uploadDocumentFile: uploadDocumentFileMutation(apiClient),
  directFileUpload: directFileUploadMutation(apiClient),
  deleteDocumentFile: deleteDocumentFileMutation(apiClient),
  moveDocumentFile: moveDocumentFileMutation(apiClient),
  documentFileContentUrl: apiClient.documentFileContentUrl,
  documentFileExportUrl: apiClient.documentFileExportUrl,
  exportDocuments: exportDocumentsMutation(apiClient),
  documentsInvalidates,
  documentTypes: documentTypesQuery(apiClient),
  createDocumentType: createDocumentTypeMutation(apiClient),
  renameDocumentType: renameDocumentTypeMutation(apiClient),
  deleteDocumentType: deleteDocumentTypeMutation(apiClient),
  documentTypesInvalidates,
  createPadSession: createPadSessionMutation(apiClient),
  activePadSession: activePadSessionQuery(apiClient),
  activePadSessionInvalidates,
  joinOwnPadSession: joinOwnPadSessionMutation(apiClient),
  sharePadSession: sharePadSessionMutation(apiClient),
  padSessionState: (sessionId: string, secret: string) =>
    padSessionStateQuery(apiClient, sessionId, secret),
  requestPadSignature: requestPadSignatureMutation(apiClient),
  setPadCurrentDocument: setPadCurrentDocumentMutation(apiClient),
  submitPadStrokes: submitPadStrokesMutation(apiClient),
  consumePadStrokes: consumePadStrokesMutation(apiClient),
  consumePadSubmission: consumePadSubmissionMutation(apiClient),
  closePadSession: closePadSessionMutation(apiClient),
  tenantSettings: tenantSettingsQuery(apiClient),
  tenantAccounts: tenantAccountsQuery(apiClient),
  updateTenantSettings: updateTenantSettingsMutation(apiClient),
  tenantSettingsInvalidates,
  signatureRecords: (documentId: string) =>
    signatureRecordsQuery(apiClient, documentId),
  createSignatureRecord: createSignatureRecordMutation(apiClient),
  signatureRecordsInvalidates,
  activeSourceUpdateRequest: (documentId: string) =>
    activeSourceUpdateRequestQuery(apiClient, documentId),
  pendingSourceUpdateRequests: pendingSourceUpdateRequestsQuery(apiClient),
  createSourceUpdateRequest: createSourceUpdateRequestMutation(apiClient),
  decideSourceUpdateRequest: decideSourceUpdateRequestMutation(apiClient),
  cancelSourceUpdateRequest: cancelSourceUpdateRequestMutation(apiClient),
  completeSourceUpdateRequest: completeSourceUpdateRequestMutation(apiClient),
  sourceUpdateRequestsInvalidates,
  disconnectPadSession: disconnectPadSessionMutation(apiClient),
  padSessionInvalidates,
  signUp: signUpMutation(authClient),
  signIn: signInMutation(authClient),
  signOut: signOutMutation(authClient),
  updateUser: updateUserMutation(authClient),
  changePassword: changePasswordMutation(authClient),
  requestMagicLink: requestMagicLinkMutation(authClient),
  requestPasswordReset: requestPasswordResetMutation(authClient),
  resetPassword: resetPasswordMutation(authClient),
  signInSocial: signInSocialMutation(authClient),
  enableTwoFactor: enableTwoFactorMutation(authClient),
  verifyTotp: verifyTotpMutation(authClient),
  disableTwoFactor: disableTwoFactorMutation(authClient),
  passkeys: passkeysQuery(authClient),
  passkeysInvalidates,
  registerPasskey: registerPasskeyMutation(authClient),
  removePasskey: removePasskeyMutation(authClient),
  signInPasskey: signInPasskeyMutation(authClient),
};

export const apiTokenActions = {
  apiTokens: apiTokensQuery(apiClient),
  createApiToken: createApiTokenMutation(apiClient),
  revokeApiToken: revokeApiTokenMutation(apiClient),
  apiTokensInvalidates,
};

export const preferenceActions = {
  userPreference: (key: string) => userPreferenceQuery(apiClient, key),
  setUserPreference: setUserPreferenceMutation(apiClient),
  userPreferenceInvalidates,
};

export const savedSearchActions = {
  savedSearches: savedSearchesQuery(apiClient),
  createSavedSearch: createSavedSearchMutation(apiClient),
  deleteSavedSearch: deleteSavedSearchMutation(apiClient),
  savedSearchesInvalidates,
};
